
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.sales.wb.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.13
 * 2014-03-19T14:33:30.775+05:30
 * Generated source version: 2.6.13
 * 
 */

@javax.jws.WebService(
                      serviceName = "MasterServiceImpService",
                      portName = "MasterServiceImpPort",
                      targetNamespace = "http://imp.service.wb.sales.com/",
                      wsdlLocation = "http://localhost:8080/Sales_Org_Service/MasterService?wsdl",
                      endpointInterface = "com.sales.wb.service.MasterService")
                      
public class MasterServiceImpl implements MasterService {

    private static final Logger LOG = Logger.getLogger(MasterServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#createEmployee(com.sales.wb.service.EmployeeMasterVO  arg0 )*
     */
    public com.sales.wb.service.Resp createEmployee(com.sales.wb.service.EmployeeMasterVO arg0) { 
        LOG.info("Executing operation createEmployee");
        System.out.println(arg0);
        try {
            com.sales.wb.service.Resp _return = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespCode = com.sales.wb.service.RespCode.FAIL;
            _return.setRespCode(_returnRespCode);
            _return.setRespMsg("RespMsg415645782");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#helloworld(*
     */
    public java.lang.String helloworld() { 
        LOG.info("Executing operation helloworld");
        try {
            java.lang.String _return = "_return-1421751687";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#getRetailerDtl(*
     */
    public com.sales.wb.service.GetRetailerResp getRetailerDtl() { 
        LOG.info("Executing operation getRetailerDtl");
        try {
            com.sales.wb.service.GetRetailerResp _return = new com.sales.wb.service.GetRetailerResp();
            com.sales.wb.service.Resp _returnResp = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespRespCode = com.sales.wb.service.RespCode.SUCCESS;
            _returnResp.setRespCode(_returnRespRespCode);
            _returnResp.setRespMsg("RespMsg688423043");
            _return.setResp(_returnResp);
            java.util.List<com.sales.wb.service.RetailerVO> _returnRetailerlist = new java.util.ArrayList<com.sales.wb.service.RetailerVO>();
            com.sales.wb.service.RetailerVO _returnRetailerlistVal1 = new com.sales.wb.service.RetailerVO();
            com.sales.wb.service.AreaVO _returnRetailerlistVal1AreaVO = new com.sales.wb.service.AreaVO();
            _returnRetailerlistVal1AreaVO.setAreaCode("AreaCode-2099712609");
            _returnRetailerlistVal1AreaVO.setAreaID(Long.valueOf(-3823369155354972527l));
            _returnRetailerlistVal1AreaVO.setAreaName("AreaName46229809");
            java.util.List<com.sales.wb.service.RetailerVO> _returnRetailerlistVal1AreaVORetailerList = new java.util.ArrayList<com.sales.wb.service.RetailerVO>();
            _returnRetailerlistVal1AreaVO.getRetailerList().addAll(_returnRetailerlistVal1AreaVORetailerList);
            _returnRetailerlistVal1.setAreaVO(_returnRetailerlistVal1AreaVO);
            _returnRetailerlistVal1.setIsActive(Boolean.valueOf(false));
            _returnRetailerlistVal1.setRetailerID(Long.valueOf(1792104501871132783l));
            _returnRetailerlistVal1.setRetailerName("RetailerName1583614799");
            _returnRetailerlistVal1.setShopAddress("ShopAddress521319743");
            _returnRetailerlistVal1.setShopName("ShopName-1677080672");
            _returnRetailerlistVal1.setShopPhoneNumber("ShopPhoneNumber-1672116865");
            _returnRetailerlist.add(_returnRetailerlistVal1);
            _return.getRetailerlist().addAll(_returnRetailerlist);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#getCompanyDetail(*
     */
    public com.sales.wb.service.GetCompanyResp getCompanyDetail() { 
        LOG.info("Executing operation getCompanyDetail");
        try {
            com.sales.wb.service.GetCompanyResp _return = new com.sales.wb.service.GetCompanyResp();
            java.util.List<com.sales.wb.service.CompanyVo> _returnCompanyList = new java.util.ArrayList<com.sales.wb.service.CompanyVo>();
            com.sales.wb.service.CompanyVo _returnCompanyListVal1 = new com.sales.wb.service.CompanyVo();
            _returnCompanyListVal1.setCompanyAddress("CompanyAddress-1915577025");
            _returnCompanyListVal1.setCompanyID(Long.valueOf(6112173189974399359l));
            _returnCompanyListVal1.setCompanyMobileNo("CompanyMobileNo-979650560");
            _returnCompanyListVal1.setCompanyName("CompanyName2142173134");
            _returnCompanyListVal1.setCompanyPhoneNo("CompanyPhoneNo-1908316729");
            _returnCompanyList.add(_returnCompanyListVal1);
            _return.getCompanyList().addAll(_returnCompanyList);
            com.sales.wb.service.Resp _returnResp = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespRespCode = com.sales.wb.service.RespCode.FAIL;
            _returnResp.setRespCode(_returnRespRespCode);
            _returnResp.setRespMsg("RespMsg-1114254557");
            _return.setResp(_returnResp);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#createArea(com.sales.wb.service.AreaVO  arg0 )*
     */
    public com.sales.wb.service.Resp createArea(com.sales.wb.service.AreaVO arg0) { 
        LOG.info("Executing operation createArea");
        System.out.println(arg0);
        try {
            com.sales.wb.service.Resp _return = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespCode = com.sales.wb.service.RespCode.FAIL;
            _return.setRespCode(_returnRespCode);
            _return.setRespMsg("RespMsg313718683");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#updateRetailer(com.sales.wb.service.RetailerVO  arg0 )*
     */
    public com.sales.wb.service.Resp updateRetailer(com.sales.wb.service.RetailerVO arg0) { 
        LOG.info("Executing operation updateRetailer");
        System.out.println(arg0);
        try {
            com.sales.wb.service.Resp _return = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespCode = com.sales.wb.service.RespCode.FAIL;
            _return.setRespCode(_returnRespCode);
            _return.setRespMsg("RespMsg-675485951");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#blockRetailer(java.lang.Long  arg0 )*
     */
    public com.sales.wb.service.Resp blockRetailer(java.lang.Long arg0) { 
        LOG.info("Executing operation blockRetailer");
        System.out.println(arg0);
        try {
            com.sales.wb.service.Resp _return = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespCode = com.sales.wb.service.RespCode.SUCCESS;
            _return.setRespCode(_returnRespCode);
            _return.setRespMsg("RespMsg-295987615");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#createBillBook(com.sales.wb.service.BillBookVo  arg0 )*
     */
    public com.sales.wb.service.Resp createBillBook(com.sales.wb.service.BillBookVo arg0) { 
        LOG.info("Executing operation createBillBook");
        System.out.println(arg0);
        try {
            com.sales.wb.service.Resp _return = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespCode = com.sales.wb.service.RespCode.FAIL;
            _return.setRespCode(_returnRespCode);
            _return.setRespMsg("RespMsg-439732274");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#blockItem(java.lang.Long  arg0 )*
     */
    public com.sales.wb.service.Resp blockItem(java.lang.Long arg0) { 
        LOG.info("Executing operation blockItem");
        System.out.println(arg0);
        try {
            com.sales.wb.service.Resp _return = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespCode = com.sales.wb.service.RespCode.FAIL;
            _return.setRespCode(_returnRespCode);
            _return.setRespMsg("RespMsg721798538");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#blockEmployee(java.lang.Long  arg0 )*
     */
    public com.sales.wb.service.Resp blockEmployee(java.lang.Long arg0) { 
        LOG.info("Executing operation blockEmployee");
        System.out.println(arg0);
        try {
            com.sales.wb.service.Resp _return = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespCode = com.sales.wb.service.RespCode.SUCCESS;
            _return.setRespCode(_returnRespCode);
            _return.setRespMsg("RespMsg1316985935");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#createRetailer(com.sales.wb.service.RetailerVO  arg0 )*
     */
    public com.sales.wb.service.Resp createRetailer(com.sales.wb.service.RetailerVO arg0) { 
        LOG.info("Executing operation createRetailer");
        System.out.println(arg0);
        try {
            com.sales.wb.service.Resp _return = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespCode = com.sales.wb.service.RespCode.SUCCESS;
            _return.setRespCode(_returnRespCode);
            _return.setRespMsg("RespMsg-143540791");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#updateEmployee(com.sales.wb.service.EmployeeMasterVO  arg0 )*
     */
    public com.sales.wb.service.Resp updateEmployee(com.sales.wb.service.EmployeeMasterVO arg0) { 
        LOG.info("Executing operation updateEmployee");
        System.out.println(arg0);
        try {
            com.sales.wb.service.Resp _return = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespCode = com.sales.wb.service.RespCode.FAIL;
            _return.setRespCode(_returnRespCode);
            _return.setRespMsg("RespMsg334679945");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#updateArea(com.sales.wb.service.AreaVO  arg0 )*
     */
    public com.sales.wb.service.Resp updateArea(com.sales.wb.service.AreaVO arg0) { 
        LOG.info("Executing operation updateArea");
        System.out.println(arg0);
        try {
            com.sales.wb.service.Resp _return = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespCode = com.sales.wb.service.RespCode.SUCCESS;
            _return.setRespCode(_returnRespCode);
            _return.setRespMsg("RespMsg1626011623");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#getAllEmployee(*
     */
    public com.sales.wb.service.GetEmployeeMasterResp getAllEmployee() { 
        LOG.info("Executing operation getAllEmployee");
        try {
            com.sales.wb.service.GetEmployeeMasterResp _return = new com.sales.wb.service.GetEmployeeMasterResp();
            java.util.List<com.sales.wb.service.EmployeeMasterVO> _returnEmployeeList = new java.util.ArrayList<com.sales.wb.service.EmployeeMasterVO>();
            com.sales.wb.service.EmployeeMasterVO _returnEmployeeListVal1 = new com.sales.wb.service.EmployeeMasterVO();
            _returnEmployeeListVal1.setEmpID(Long.valueOf(573425434101787066l));
            _returnEmployeeListVal1.setEmpName("EmpName-98218519");
            _returnEmployeeListVal1.setIsActive(Boolean.valueOf(true));
            _returnEmployeeList.add(_returnEmployeeListVal1);
            _return.getEmployeeList().addAll(_returnEmployeeList);
            com.sales.wb.service.Resp _returnResp = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespRespCode = com.sales.wb.service.RespCode.FAIL;
            _returnResp.setRespCode(_returnRespRespCode);
            _returnResp.setRespMsg("RespMsg1657828492");
            _return.setResp(_returnResp);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#getAllPaymentModes(*
     */
    public com.sales.wb.service.GetPaymentModeResp getAllPaymentModes() { 
        LOG.info("Executing operation getAllPaymentModes");
        try {
            com.sales.wb.service.GetPaymentModeResp _return = new com.sales.wb.service.GetPaymentModeResp();
            java.util.List<com.sales.wb.service.PaymentModeVo> _returnPaymentModeList = new java.util.ArrayList<com.sales.wb.service.PaymentModeVo>();
            com.sales.wb.service.PaymentModeVo _returnPaymentModeListVal1 = new com.sales.wb.service.PaymentModeVo();
            _returnPaymentModeListVal1.setPaymentModeId(628817216);
            _returnPaymentModeListVal1.setPaymentModeName("PaymentModeName1149131516");
            _returnPaymentModeList.add(_returnPaymentModeListVal1);
            _return.getPaymentModeList().addAll(_returnPaymentModeList);
            com.sales.wb.service.Resp _returnResp = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespRespCode = com.sales.wb.service.RespCode.FAIL;
            _returnResp.setRespCode(_returnRespRespCode);
            _returnResp.setRespMsg("RespMsg-1595224440");
            _return.setResp(_returnResp);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#getAllBillBookdtl(*
     */
    public com.sales.wb.service.GetAllBillBookDtlResp getAllBillBookdtl() { 
        LOG.info("Executing operation getAllBillBookdtl");
        try {
            com.sales.wb.service.GetAllBillBookDtlResp _return = new com.sales.wb.service.GetAllBillBookDtlResp();
            java.util.List<com.sales.wb.service.BillBookVo> _returnBillBookList = new java.util.ArrayList<com.sales.wb.service.BillBookVo>();
            com.sales.wb.service.BillBookVo _returnBillBookListVal1 = new com.sales.wb.service.BillBookVo();
            _returnBillBookListVal1.setBillBookId(Long.valueOf(7170487705196802275l));
            _returnBillBookListVal1.setBillBookNum("BillBookNum-896999528");
            _returnBillBookListVal1.setEndRange("EndRange10670536");
            _returnBillBookListVal1.setStartRange("StartRange-795715224");
            _returnBillBookList.add(_returnBillBookListVal1);
            _return.getBillBookList().addAll(_returnBillBookList);
            com.sales.wb.service.Resp _returnResp = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespRespCode = com.sales.wb.service.RespCode.SUCCESS;
            _returnResp.setRespCode(_returnRespRespCode);
            _returnResp.setRespMsg("RespMsg-250055453");
            _return.setResp(_returnResp);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#updateBillbook(com.sales.wb.service.BillBookVo  arg0 )*
     */
    public com.sales.wb.service.Resp updateBillbook(com.sales.wb.service.BillBookVo arg0) { 
        LOG.info("Executing operation updateBillbook");
        System.out.println(arg0);
        try {
            com.sales.wb.service.Resp _return = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespCode = com.sales.wb.service.RespCode.SUCCESS;
            _return.setRespCode(_returnRespCode);
            _return.setRespMsg("RespMsg1926957910");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#getAllItemMasterDtl(*
     */
    public com.sales.wb.service.GetItemMasterResp getAllItemMasterDtl() { 
        LOG.info("Executing operation getAllItemMasterDtl");
        try {
            com.sales.wb.service.GetItemMasterResp _return = new com.sales.wb.service.GetItemMasterResp();
            java.util.List<com.sales.wb.service.ItemMasterVO> _returnList = new java.util.ArrayList<com.sales.wb.service.ItemMasterVO>();
            com.sales.wb.service.ItemMasterVO _returnListVal1 = new com.sales.wb.service.ItemMasterVO();
            _returnListVal1.setActive(Boolean.valueOf(false));
            _returnListVal1.setItemCode("ItemCode2065376102");
            _returnListVal1.setItemId(Long.valueOf(6387869391992938291l));
            _returnListVal1.setItemName("ItemName367981606");
            _returnList.add(_returnListVal1);
            _return.getList().addAll(_returnList);
            com.sales.wb.service.Resp _returnResp = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespRespCode = com.sales.wb.service.RespCode.FAIL;
            _returnResp.setRespCode(_returnRespRespCode);
            _returnResp.setRespMsg("RespMsg-1226035808");
            _return.setResp(_returnResp);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#updateItem(com.sales.wb.service.ItemMasterVO  arg0 )*
     */
    public com.sales.wb.service.Resp updateItem(com.sales.wb.service.ItemMasterVO arg0) { 
        LOG.info("Executing operation updateItem");
        System.out.println(arg0);
        try {
            com.sales.wb.service.Resp _return = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespCode = com.sales.wb.service.RespCode.FAIL;
            _return.setRespCode(_returnRespCode);
            _return.setRespMsg("RespMsg-800439407");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#getAreaMasterDtl(*
     */
    public com.sales.wb.service.GetAreaDtlResp getAreaMasterDtl() { 
        LOG.info("Executing operation getAreaMasterDtl");
        try {
            com.sales.wb.service.GetAreaDtlResp _return = new com.sales.wb.service.GetAreaDtlResp();
            java.util.List<com.sales.wb.service.AreaVO> _returnList = new java.util.ArrayList<com.sales.wb.service.AreaVO>();
            com.sales.wb.service.AreaVO _returnListVal1 = new com.sales.wb.service.AreaVO();
            _returnListVal1.setAreaCode("AreaCode1516536616");
            _returnListVal1.setAreaID(Long.valueOf(-2847520548202560317l));
            _returnListVal1.setAreaName("AreaName-1739926027");
            java.util.List<com.sales.wb.service.RetailerVO> _returnListVal1RetailerList = new java.util.ArrayList<com.sales.wb.service.RetailerVO>();
            _returnListVal1.getRetailerList().addAll(_returnListVal1RetailerList);
            _returnList.add(_returnListVal1);
            _return.getList().addAll(_returnList);
            com.sales.wb.service.Resp _returnResp = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespRespCode = com.sales.wb.service.RespCode.SUCCESS;
            _returnResp.setRespCode(_returnRespRespCode);
            _returnResp.setRespMsg("RespMsg-21747656");
            _return.setResp(_returnResp);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sales.wb.service.MasterService#createItem(com.sales.wb.service.ItemMasterVO  arg0 )*
     */
    public com.sales.wb.service.Resp createItem(com.sales.wb.service.ItemMasterVO arg0) { 
        LOG.info("Executing operation createItem");
        System.out.println(arg0);
        try {
            com.sales.wb.service.Resp _return = new com.sales.wb.service.Resp();
            com.sales.wb.service.RespCode _returnRespCode = com.sales.wb.service.RespCode.SUCCESS;
            _return.setRespCode(_returnRespCode);
            _return.setRespMsg("RespMsg-307029410");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
