package com.sales.wb.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.13
 * 2014-03-19T14:33:30.813+05:30
 * Generated source version: 2.6.13
 * 
 */
@WebService(targetNamespace = "http://service.wb.sales.com/", name = "MasterService")
@XmlSeeAlso({ObjectFactory.class})
public interface MasterService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createEmployee", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.CreateEmployee")
    @WebMethod
    @ResponseWrapper(localName = "createEmployeeResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.CreateEmployeeResponse")
    public com.sales.wb.service.Resp createEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sales.wb.service.EmployeeMasterVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "helloworld", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.Helloworld")
    @WebMethod
    @ResponseWrapper(localName = "helloworldResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.HelloworldResponse")
    public java.lang.String helloworld();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRetailerDtl", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.GetRetailerDtl")
    @WebMethod
    @ResponseWrapper(localName = "getRetailerDtlResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.GetRetailerDtlResponse")
    public com.sales.wb.service.GetRetailerResp getRetailerDtl();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCompanyDetail", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.GetCompanyDetail")
    @WebMethod
    @ResponseWrapper(localName = "getCompanyDetailResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.GetCompanyDetailResponse")
    public com.sales.wb.service.GetCompanyResp getCompanyDetail();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createArea", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.CreateArea")
    @WebMethod
    @ResponseWrapper(localName = "createAreaResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.CreateAreaResponse")
    public com.sales.wb.service.Resp createArea(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sales.wb.service.AreaVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateRetailer", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.UpdateRetailer")
    @WebMethod
    @ResponseWrapper(localName = "updateRetailerResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.UpdateRetailerResponse")
    public com.sales.wb.service.Resp updateRetailer(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sales.wb.service.RetailerVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "blockRetailer", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.BlockRetailer")
    @WebMethod
    @ResponseWrapper(localName = "blockRetailerResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.BlockRetailerResponse")
    public com.sales.wb.service.Resp blockRetailer(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createBillBook", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.CreateBillBook")
    @WebMethod
    @ResponseWrapper(localName = "createBillBookResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.CreateBillBookResponse")
    public com.sales.wb.service.Resp createBillBook(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sales.wb.service.BillBookVo arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "blockItem", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.BlockItem")
    @WebMethod
    @ResponseWrapper(localName = "blockItemResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.BlockItemResponse")
    public com.sales.wb.service.Resp blockItem(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "blockEmployee", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.BlockEmployee")
    @WebMethod
    @ResponseWrapper(localName = "blockEmployeeResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.BlockEmployeeResponse")
    public com.sales.wb.service.Resp blockEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createRetailer", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.CreateRetailer")
    @WebMethod
    @ResponseWrapper(localName = "createRetailerResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.CreateRetailerResponse")
    public com.sales.wb.service.Resp createRetailer(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sales.wb.service.RetailerVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.UpdateEmployee")
    @WebMethod
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.UpdateEmployeeResponse")
    public com.sales.wb.service.Resp updateEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sales.wb.service.EmployeeMasterVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateArea", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.UpdateArea")
    @WebMethod
    @ResponseWrapper(localName = "updateAreaResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.UpdateAreaResponse")
    public com.sales.wb.service.Resp updateArea(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sales.wb.service.AreaVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllEmployee", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.GetAllEmployee")
    @WebMethod
    @ResponseWrapper(localName = "getAllEmployeeResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.GetAllEmployeeResponse")
    public com.sales.wb.service.GetEmployeeMasterResp getAllEmployee();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllPaymentModes", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.GetAllPaymentModes")
    @WebMethod
    @ResponseWrapper(localName = "getAllPaymentModesResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.GetAllPaymentModesResponse")
    public com.sales.wb.service.GetPaymentModeResp getAllPaymentModes();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllBillBookdtl", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.GetAllBillBookdtl")
    @WebMethod
    @ResponseWrapper(localName = "getAllBillBookdtlResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.GetAllBillBookdtlResponse")
    public com.sales.wb.service.GetAllBillBookDtlResp getAllBillBookdtl();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateBillbook", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.UpdateBillbook")
    @WebMethod
    @ResponseWrapper(localName = "updateBillbookResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.UpdateBillbookResponse")
    public com.sales.wb.service.Resp updateBillbook(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sales.wb.service.BillBookVo arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllItemMasterDtl", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.GetAllItemMasterDtl")
    @WebMethod
    @ResponseWrapper(localName = "getAllItemMasterDtlResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.GetAllItemMasterDtlResponse")
    public com.sales.wb.service.GetItemMasterResp getAllItemMasterDtl();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateItem", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.UpdateItem")
    @WebMethod
    @ResponseWrapper(localName = "updateItemResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.UpdateItemResponse")
    public com.sales.wb.service.Resp updateItem(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sales.wb.service.ItemMasterVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAreaMasterDtl", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.GetAreaMasterDtl")
    @WebMethod
    @ResponseWrapper(localName = "getAreaMasterDtlResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.GetAreaMasterDtlResponse")
    public com.sales.wb.service.GetAreaDtlResp getAreaMasterDtl();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createItem", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.CreateItem")
    @WebMethod
    @ResponseWrapper(localName = "createItemResponse", targetNamespace = "http://service.wb.sales.com/", className = "com.sales.wb.service.CreateItemResponse")
    public com.sales.wb.service.Resp createItem(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sales.wb.service.ItemMasterVO arg0
    );
}
