package com.sales.wb.service.imp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.sales.wb.service.MasterService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.13
 * 2014-03-19T14:33:30.837+05:30
 * Generated source version: 2.6.13
 * 
 */
@WebServiceClient(name = "MasterServiceImpService", 
                  wsdlLocation = "http://localhost:8080/Sales_Org_Service/MasterService?wsdl",
                  targetNamespace = "http://imp.service.wb.sales.com/") 
public class MasterServiceImpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://imp.service.wb.sales.com/", "MasterServiceImpService");
    public final static QName MasterServiceImpPort = new QName("http://imp.service.wb.sales.com/", "MasterServiceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Sales_Org_Service/MasterService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MasterServiceImpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Sales_Org_Service/MasterService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MasterServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MasterServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MasterServiceImpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns MasterService
     */
    @WebEndpoint(name = "MasterServiceImpPort")
    public MasterService getMasterServiceImpPort() {
        return super.getPort(MasterServiceImpPort, MasterService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MasterService
     */
    @WebEndpoint(name = "MasterServiceImpPort")
    public MasterService getMasterServiceImpPort(WebServiceFeature... features) {
        return super.getPort(MasterServiceImpPort, MasterService.class, features);
    }

}
